name: PHP Unit Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kode repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setup PHP Environment
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: curl, mbstring

    # 3. Install Dependency (PHPUnit)
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    # 4. Jalankan Testing dengan Environment Variable (Secret) 
    - name: Run PHPUnit Tests
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: vendor/bin/phpunit tests/FileTypeTest.php
